; Automatisch erzeugt von tools/tastatur.py - nicht von Hand aendern.
; MEGA65-Belegung: Paare (Scancode, Zeichen), Ende mit 0
m65_listen
m65_l_normal
	.byte $4c,$3a,$52,$3b,$54,$40,$55,$3d,$61,$5f,$00
m65_l_shift
	.byte $26,$23,$3d,$27,$45,$7b,$5b,$00,$4a,$00,$49,$3e,$41,$3c,$4c,$5b,$52,$5d,$54,$00,$55,$5f,$5d,$00,$7c,$00,$0e,$00,$61,$60,$66,$0e,$00
m65_l_mega
	.byte $49,$7c,$4c,$7b,$41,$7e,$52,$7d,$61,$60,$00
m65_l_alt
	.byte $1c,$e4,$44,$f6,$3c,$fc,$1b,$df,$00
m65_l_altshift
	.byte $1c,$c4,$44,$d6,$3c,$dc,$00
m65_l_e0shift
	.byte $4a,$3f,$74,$1d,$72,$1e,$00
m65_l_e0mega
	.byte $4a,$5c,$00
m65_l_ftasten
	.byte $05,$06,$04,$0c,$03,$0b,$83,$0a,$01,$09,$78,$07,$08,$10,$00
